# yamllint disable rule:braces rule:commas rule:colons rule:comments-indentation
---
window:
    # Blank space added around the window in pixels
    padding:
        x: 0
        y: 0

    # Spread additional padding evenly around the terminal content
    dynamic_padding: true

    # Disable border and title bar
    decorations: none

font:
    normal:
        family: Hack Nerd Font Mono
        style: Regular
    bold:
        family: Hack Nerd Font Mono
        style: Bold
    italic:
        family: Hack Nerd Font Mono
        style: Italic

    # Point size of the font
    size: 24 

# Colors (One Dark); if dim colors are not set, they will be calculated
# automatically based on the `normal` colors
import:
  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml

mouse:
    hide_when_typing: true

selection:
    # When set to `true`, selected text will be copied to the primary
    # clipboard.
    save_to_clipboard: true

cursor:
    # Thickness of the cursor (number from `0.0` to `1.0`)
    thickness: 0.18
    # Vi mode cursor style
    vi_mode_style: Block

# Default shell
# For osx uncomment the following
    # shell:
        # program: /usr/local/bin/bash  # osx
    # args:
    # - --login

