#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

#### ==== Unused ===== ##
## # This is used to determine if a monitor is used
## # Since the notch is -only- on the laptop, if a monitor isn't used,
## # then that means the internal display is used ¯\_(ツ)_/¯
## #
## MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')
## 
## if [[ $MAIN_DISPLAY = "Built-in" ]]; then
##     source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
## else
##     source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
## fi

source "$HOME/.config/sketchybar/colors.sh"

FONT="Monaspace Krypton"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=30 \
    color=$BAR_COLOR \
    margin=0 \
    sticky=on \
    padding_left=2 \
    padding_right=2 \
    notch_width=188 \
    display=all

sketchybar --default \
    background.height=32 \
    icon.color=$WHITE \
    icon.font="$FONT:Medium:14.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=$WHITE\
    label.font="$FONT:Bold:10.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=10

## LEFT
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0xfff7287fd\
        background.corner_radius=5 \
        label.color=$WHITE \
        background.height=18 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=40\
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    background.color=0x00000000 \
    icon.color=0xffa6da95 \
    icon.font="$FONT:Bold:18.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT:Bold:14.0" \
    label.color=$GREEN \
    label.padding_left=5
    label.padding_right=5

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

# Center

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon=󰓇 \
    label.padding_left=5 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

# Right
#
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/brew.sh"

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    label.color=$ROSEWATER \
    icon.color=$ROSEWATER \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
